builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
